import Navigation from "@/components/navigation";
import "../styles/global.css"
export const metadata = {
  title: { template: "%s | Next Movies", default: "asdf" },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        layout
        {children}
      </body>
    </html>
  );
}
